apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-prod
  annotations:
    argocd-image-updater.argoproj.io/image-list: flask=zahidbilal/flask-gitops
    argocd-image-updater.argoproj.io/flask.update-strategy: latest
spec:
  source:
    repoURL: https://github.com/zahidbilal/gitops-eks-flask.git
    path: helm/flask-app
    targetRevision: prod
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
