apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: flask=zahidbilal/flask-gitops
    argocd-image-updater.argoproj.io/flask.update-strategy: latest
    argocd-image-updater.argoproj.io/flask.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/flask.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: staging
    # Staging can auto-update but with filters
    argocd-image-updater.argoproj.io/flask.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/zahid-IT/gitops-eks-flask.git
    targetRevision: staging
    path: helm/flask-app
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true      # Auto-prune for staging
      selfHeal: true   # Auto-heal for staging
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
