pipeline {
  agent any

  environment {
    IMAGE = "zahidbilal/flask-gitops"
    BASE_VERSION = "1.0"
    DOCKER_CREDENTIALS = "dockerhub-creds"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Set Version') {
      steps {
        script {
          def envName = env.BRANCH_NAME
          def version = "${BASE_VERSION}.${env.BUILD_NUMBER}"

          env.VERSION_TAG = "${envName}-${version}"
          env.LATEST_TAG  = "${envName}-latest"

          echo "Version tag: ${env.VERSION_TAG}"
          echo "Latest tag: ${env.LATEST_TAG}"
        }
      }
    }

    stage('Build Image') {
      steps {
        sh """
          docker build -f docker/Dockerfile \
            -t ${IMAGE}:${VERSION_TAG} \
            -t ${IMAGE}:${LATEST_TAG} .
        """
      }
    }

    stage('Push Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: DOCKER_CREDENTIALS,
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh """
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ${IMAGE}:${VERSION_TAG}
            docker push ${IMAGE}:${LATEST_TAG}
          """
        }
      }
    }
  }
}
