pipeline {
  agent any

  environment {
    IMAGE = "zahidbilal/flask-gitops"
    BASE_VERSION = "1.0"
  }

  stages {

    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Set Version') {
      steps {
        script {
          def envName = env.BRANCH_NAME
          def version = "${BASE_VERSION}.${env.BUILD_NUMBER}"

          env.VERSION_TAG = "${envName}-${version}"
          env.LATEST_TAG  = "${envName}-latest"
        }
      }
    }

    stage('Build Image') {
      steps {
        sh """
          docker build -f docker/Dockerfile \
            -t ${IMAGE}:${VERSION_TAG} \
            -t ${IMAGE}:${LATEST_TAG} .
        """
      }
    }

    stage('Push Image') {
      steps {
        withCredentials([string(credentialsId: 'dockerhub-pass', variable: 'PASS')]) {
          sh """
            echo $PASS | docker login -u zahidbilal --password-stdin
            docker push ${IMAGE}:${VERSION_TAG}
            docker push ${IMAGE}:${LATEST_TAG}
          """
        }
      }
    }
  }
}
